version: 0.2
phases:
  install:
    commands:
      - sam package --template-file template.yaml --s3-bucket michi-cloudchallenge --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml